/**
 * Senate Floor Scheduler — live-data + chat backend (Cloudflare Worker scaffold).
 *
 * Deploy:  npx wrangler deploy server/worker.js
 * Secrets: npx wrangler secret put ANTHROPIC_API_KEY
 *          npx wrangler secret put CONGRESS_API_KEY   (free key: https://api.congress.gov/sign-up)
 *
 * Then in the app's chat, type:  connect api https://<your-worker>.workers.dev
 *
 * Endpoints:
 *   GET  /api/status   — live status of H.R. 3633 from the official Congress.gov API
 *   POST /api/chat     — Claude-powered "Ask the Parliamentarian" ({question, state})
 *   GET  /api/signals  — news-tracker signals (RSS-based; see the honesty note below)
 *
 * Social-signal honesty note: X (Twitter) and Truth Social prohibit scraping in their
 * terms of service, and neither offers a free read API suitable for this. The /api/signals
 * adapter therefore aggregates sources that ARE permitted: official RSS feeds (Politico,
 * The Hill, Punchbowl newsletters where licensed), Senate press-office feeds, and the
 * Congress.gov actions feed. If your team licenses the X API (paid tiers permit this) or
 * a monitoring vendor (Quorum, FiscalNote, TweetDeck-style tools), plug it into
 * fetchSocialSignals() below — the shape is ready.
 */

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};
const json = (obj, status = 200) =>
  new Response(JSON.stringify(obj), { status, headers: { 'Content-Type': 'application/json', ...CORS } });

const SYSTEM_PROMPT = `You are the "Parliamentarian's desk" assistant inside a Senate floor-scheduling
tool. You answer questions about U.S. Senate floor procedure with precision: Rule XXII cloture mechanics
(16-senator petition; ripens one hour after convening on the second session day after filing; 60 votes =
three-fifths sworn for legislation, 51 by precedent for nominations; 30 hours post-cloture, 2 hours for
district judges since 2019), debatable vs. privileged motions to proceed, Rule XIV, filling the amendment
tree, unanimous consent and holds, reconciliation and the Byrd rule, the nuclear option, amendment
exchange ("ping-pong"), and the realities of floor scheduling (the Leader's right of first recognition,
floor-time scarcity, recess calendars). Cite the governing rule or precedent when you state a mechanic.
Be candid about political feasibility, and clearly separate (a) what the rules require, (b) what can be
waived by consent, and (c) what requires creating new precedent. If the user's question depends on current
bill status, prefer the CONTEXT block provided with the request over your training data, and say when you
are unsure. Keep answers focused — a floor staffer is reading this between votes.`;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS });

    try {
      if (url.pathname === '/api/status') return await billStatus(env);
      if (url.pathname === '/api/chat' && request.method === 'POST') return await chat(request, env);
      if (url.pathname === '/api/signals') return await signals(env);
    } catch (err) {
      return json({ error: String(err && err.message || err) }, 502);
    }
    return json({ error: 'not found' }, 404);
  },
};

/* ---------- Live bill status (Congress.gov official API) ---------- */
async function billStatus(env) {
  const base = 'https://api.congress.gov/v3/bill/119/hr/3633';
  const key = `api_key=${env.CONGRESS_API_KEY}&format=json`;
  const [bill, actions] = await Promise.all([
    fetch(`${base}?${key}`).then(r => r.json()),
    fetch(`${base}/actions?limit=10&${key}`).then(r => r.json()),
  ]);
  return json({
    title: bill?.bill?.title,
    latestAction: bill?.bill?.latestAction,
    recentActions: (actions?.actions || []).map(a => ({ date: a.actionDate, text: a.text })),
    fetched: new Date().toISOString(),
  });
}

/* ---------- Claude-powered parliamentarian chat ---------- */
async function chat(request, env) {
  const { question, state } = await request.json();
  if (!question) return json({ error: 'question required' }, 400);

  const context = state
    ? `\n\nCONTEXT — the user's current scheduler state (a floor memo generated by the tool):\n${state.memo || ''}`
    : '';

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
      'anthropic-beta': 'server-side-fallback-2026-07-01',
    },
    body: JSON.stringify({
      model: 'claude-opus-5',
      max_tokens: 2048,
      fallbacks: 'default',
      system: [{ type: 'text', text: SYSTEM_PROMPT, cache_control: { type: 'ephemeral' } }],
      messages: [{ role: 'user', content: question + context }],
    }),
  });
  if (!res.ok) return json({ error: `anthropic ${res.status}: ${await res.text()}` }, 502);
  const msg = await res.json();
  if (msg.stop_reason === 'refusal') {
    return json({ answer: '<p>The live assistant declined that request — try rephrasing.</p>' });
  }
  const text = (msg.content || []).filter(b => b.type === 'text').map(b => b.text).join('\n');
  // Minimal markdown→HTML for the chat bubble (paragraphs + bold).
  const html = text.split(/\n{2,}/).map(p =>
    '<p>' + p.replace(/&/g, '&amp;').replace(/</g, '&lt;')
             .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>') + '</p>'
  ).join('');
  return json({ answer: html });
}

/* ---------- News & social signals ---------- */
async function signals(env) {
  const items = [];
  // Politico Congress RSS (permitted; check your organization's licensing for full-text use).
  try {
    const rss = await fetch('https://rss.politico.com/congress.xml').then(r => r.text());
    for (const m of rss.matchAll(/<item>[\s\S]*?<title>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?<\/title>[\s\S]*?<link>(.*?)<\/link>[\s\S]*?<\/item>/g)) {
      if (/clarity|crypto|market structure|senate floor|cloture/i.test(m[1]))
        items.push({ source: 'Politico', title: m[1], url: m[2] });
    }
  } catch (_) { /* feed unavailable — degrade gracefully */ }
  const social = await fetchSocialSignals(env);
  return json({ items: items.slice(0, 10), social, fetched: new Date().toISOString() });
}

/**
 * Plug licensed social-media sources in here. Deliberately returns a stub until you do:
 * scraping X/Truth Social violates their ToS, so this scaffold won't do it. Options that
 * comply: the paid X API v2 (filtered stream on member handles), a monitoring vendor's
 * API, or a human-in-the-loop paste flow.
 */
async function fetchSocialSignals(_env) {
  return { available: false, note: 'Connect a licensed X API or monitoring vendor here.' };
}
